music_directory	"$XDG_MUSIC_DIR"
playlist_directory "$XDG_CONFIG_HOME/mpd/playlists"

db_file "$XDG_CACHE_HOME/mpd/database"
state_file "$HOME/.local/state/mpd/state"
sticker_file "$XDG_CACHE_HOME/sticker.sql"

restore_paused "yes"
auto_update	"yes"

port "6600"

audio_output {
	type "pipewire"
    name "PipeWire Sound Server"
}

audio_output {
    type "fifo"
    name "visualizer"
    path "$XDG_CACHE_HOME/mpd/mpd.fifo"
    format "44100:16:2"
}

replaygain "track"
